/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GetCsolRouteImport } from './routes/get-csol'
import { Route as CreateAuctionRouteImport } from './routes/create-auction'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionsIdRouteImport } from './routes/auctions_.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GetCsolRoute = GetCsolRouteImport.update({
  id: '/get-csol',
  path: '/get-csol',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAuctionRoute = CreateAuctionRouteImport.update({
  id: '/create-auction',
  path: '/create-auction',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/auctions_/$id',
  path: '/auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/create-auction': typeof CreateAuctionRoute
  '/get-csol': typeof GetCsolRoute
  '/profile': typeof ProfileRoute
  '/auctions/$id': typeof AuctionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/create-auction': typeof CreateAuctionRoute
  '/get-csol': typeof GetCsolRoute
  '/profile': typeof ProfileRoute
  '/auctions/$id': typeof AuctionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/create-auction': typeof CreateAuctionRoute
  '/get-csol': typeof GetCsolRoute
  '/profile': typeof ProfileRoute
  '/auctions_/$id': typeof AuctionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auctions'
    | '/create-auction'
    | '/get-csol'
    | '/profile'
    | '/auctions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auctions'
    | '/create-auction'
    | '/get-csol'
    | '/profile'
    | '/auctions/$id'
  id:
    | '__root__'
    | '/'
    | '/auctions'
    | '/create-auction'
    | '/get-csol'
    | '/profile'
    | '/auctions_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsRoute: typeof AuctionsRoute
  CreateAuctionRoute: typeof CreateAuctionRoute
  GetCsolRoute: typeof GetCsolRoute
  ProfileRoute: typeof ProfileRoute
  AuctionsIdRoute: typeof AuctionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-csol': {
      id: '/get-csol'
      path: '/get-csol'
      fullPath: '/get-csol'
      preLoaderRoute: typeof GetCsolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-auction': {
      id: '/create-auction'
      path: '/create-auction'
      fullPath: '/create-auction'
      preLoaderRoute: typeof CreateAuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions_/$id': {
      id: '/auctions_/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsRoute: AuctionsRoute,
  CreateAuctionRoute: CreateAuctionRoute,
  GetCsolRoute: GetCsolRoute,
  ProfileRoute: ProfileRoute,
  AuctionsIdRoute: AuctionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
